name: update_ts

on:
  pull_request:
    branch: "*"
  push:
    branch: "*"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update the timestamp file
        run: printf ${{ github.actor }}
