name: get_context

on:
  pull_request:
    branch: "*"
  push:
    branch: "*"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: print github context
        run: printf ${{ github }}
