name: update_ts

on:
  pull_request:
    branch: "main"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update the timestamp file
        run: date >> timestamp.txt && cat timestamp.txt
      - name: Commit report
        run: |
          git config --local user.email "jubelcassioverridasilva@github.com"
          git config --local user.name "Jubel Cassio"
          git add .
          git commit -am "Automated Report"
          git push
