name: update_ts

on:
<<<<<<< HEAD
  push:
    tags: "release*"
=======
  pull_request:
    branch: "main"
    types: [closed]

>>>>>>> 715751f68dde79437e107a3746cfdb864e2183d9
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update the timestamp file
        run: date >> timestamp.txt && cat timestamp.txt
      - name: Commit report
        run: |
          git config --global user.name 'Jubel Cassio'
          git config --global user.email 'jubelcassioverridasilva@gmail.com'
          git add .
          git commit -am "Automated report"
          git push
